version: "3.8"

services:
    server:
        build: server/
        command: bash -c "uvicorn src.main:app --host 0.0.0.0 --port 9000 --reload"
        volumes:
            - ./server/src:/server/src
        ports:
            - 9000
        networks:
            - back-tier

    client:
        build: client/
        volumes:
            - ./client/src:/client/src
            - ./client/vite.config.ts:/client/vite.config.ts
        ports:
            - 3000
        networks:
            - back-tier
        links:
            - server

    proxy:
        image: nginx:stable-alpine
        ports:
            - 8080:8080
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        networks:
            - front-tier
            - back-tier
        links:
            - client
            - server
        depends_on:
            - client
            - server

networks:
    front-tier:
        attachable: true
    back-tier: {}

