version: "3.8"

services:
    database:
      image: postgres:latest
      restart: always
      environment:
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: 12345
        POSTGRES_DB: volo_db
      ports:
        - "5432:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data
      networks:
        - back-tier


    server:
        build: server/
        command: bash -c "uvicorn src.main:app --host 0.0.0.0 --port 9000 --reload"
        volumes:
            - ./server/src:/server/src
        environment:
          DATABASE_HOST: database
          DATABASE_USER: admin
          DATABASE_PASSWORD: 12345 
          DATABASE_NAME: volo_db

        ports:
            - 9000
        networks:
            - back-tier
        depends_on:
            - database

    client:
        build: client/
        volumes:
            - ./client/src:/client/src
            - ./client/vite.config.ts:/client/vite.config.ts
        ports:
            - 3000
        networks:
            - back-tier
        links:
            - server

    proxy:
        image: nginx:stable-alpine
        ports:
            - 8080:8080
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        networks:
            - front-tier
            - back-tier
        links:
            - client
            - server
        depends_on:
            - client
            - server

networks:
    front-tier:
        attachable: true
    back-tier: {}

volumes:
  postgres_data:
